[versions]
agp = "8.3.1"
appcenter = "5.0.4"
appcompat = "1.6.1"
borderview = "1.1.0"
constraintlayout = "2.1.4"
core-ktx = "1.12.0"
drakeet-about = "2.5.2"
espresso-core = "3.5.1"
exifinterface = "1.3.7"
flexbox = "3.0.0"
fragment-ktx = "1.6.2"
glide = "4.16.0"
glide-transformations = "4.3.0"
hilt = "2.51.1"
immersionbar = "3.2.2"
jbcrypt = "0.4"
jsoup = "1.17.2"
junit = "4.13.2"
junit-version = "1.1.5"
kotlin = "1.9.23"
kotlin-stdlib = "1.9.23"
ksp = "1.9.23-1.0.20"
leakcanary = "2.13"
lifecycle-extensions = "2.2.0"
lifecycle-livedata-ktx = "2.7.0"
material = "1.11.0"
material-preference = "2.0.0"
material-version = "2.7.0"
materialthemebuilder = "1.4.1"
okhttp = "4.12.0"
preference-ktx = "1.2.1"
recyclerview = "1.3.2"
retrofit = "2.11.0"
room = "2.6.1"
sketch-gif = "2.7.1"
swiperefreshlayout = "1.1.0"
utils = "1.1.5.4"
viewpager2 = "1.0.0"
webkit = "1.10.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
androidx-ext-junit = { module = "androidx.test.ext:junit", version.ref = "junit-version" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle-livedata-ktx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-livedata-ktx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
appcenter-crashes = { module = "com.microsoft.appcenter:appcenter-crashes", version.ref = "appcenter" }
appcenter-analytics = { module = "com.microsoft.appcenter:appcenter-analytics", version.ref = "appcenter" }
drakeet-about = { module = "com.drakeet.about:about", version.ref = "drakeet-about" }
google-android-material = { module = "com.google.android.material:material", version.ref = "material" }
google-android-flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
google-dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
glide-okhttp3-integration = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "glide" }
glide-transformations = { module = "jp.wasabeef:glide-transformations", version.ref = "glide-transformations" }
immersionbar = { module = "com.geyifeng.immersionbar:immersionbar", version.ref = "immersionbar" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
jbcrypt = { module = "org.mindrot:jbcrypt", version.ref = "jbcrypt" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-stdlib" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
rikkax-borderview = { module = "dev.rikka.rikkax.widget:borderview", version.ref = "borderview" }
rikkax-material = { module = "dev.rikka.rikkax.material:material", version.ref = "material-version" }
rikkax-material-preference = { module = "dev.rikka.rikkax.material:material-preference", version.ref = "material-preference" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
sketch-gif = { module = "me.panpf:sketch-gif", version.ref = "sketch-gif" }
zhaobozhen-libraries-utils = { module = "com.github.zhaobozhen.libraries:utils", version.ref = "utils" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
rikka-tools-materialthemebuilder = { id = "dev.rikka.tools.materialthemebuilder", version.ref = "materialthemebuilder" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
